[package]
name = "test-env-log"
version = "0.2.1"
authors = ["Daniel Mueller <deso@posteo.net>"]
edition = "2018"
license = "Apache-2.0 OR MIT"
homepage = "https://github.com/d-e-s-o/test-env-log"
repository = "https://github.com/d-e-s-o/test-env-log.git"
readme = "README.md"
categories = [
  "development-tools::testing",
  "development-tools",
  "config",
  "api-bindings",
]
keywords = [
  "env_logger",
  "log",
  "logging",
  "testing",
  "tests",
]
description = """
A replacement of the #[test] attribute that initializes the env_logger
before running tests.
"""

[badges]
gitlab = { repository = "d-e-s-o/test-env-log", branch = "master" }

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = {version = "1.0"}
syn = {version = "1.0", features = ["full"]}

[dev-dependencies]
env_logger = {version = "0.7", default-features = false}
log = "0.4"
tokio = {version = "0.2", default-features = false, features = ["rt-core", "macros"]}
