# Copyright (C) 2022 Daniel Mueller <deso@posteo.net>
# SPDX-License-Identifier: GPL-3.0-or-later

name: CI

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  test:
    name: Build and test [${{ matrix.rust }}, ${{ matrix.profile }}]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rust: [1.49.0, stable]
        profile: [dev, release]
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
        profile: minimal
        override: true
    - if: ${{ matrix.profile == 'dev' }}
      name: Build & test dev
      run: |
        cargo build
        cargo build --all-features
        cargo test
    # We need to duplicate the logic here, because up to 1.56 Cargo
    # considers the --profile option unstable. Once our minimum
    # supported Rust version is above that, we should remove the above
    # block.
    - if: ${{ matrix.rust == 'stable' && matrix.profile != 'dev'}}
      name: Build & test release
      run: |
        cargo build --profile=${{ matrix.profile }}
        cargo build --all-features --profile=${{ matrix.profile }}
        cargo test --profile=${{ matrix.profile }}
  clippy:
    name: Lint with clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy
          override: true
      - run: cargo clippy --no-deps --all-targets --all-features -- -A unknown_lints -D warnings
  cargo-doc:
    name: Generate documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - run: cargo doc --no-deps
